# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20, null=True, unique=True)),
                ('senha', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True, unique=True)),
                ('link', models.CharField(max_length=20, null=True, unique=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Categoria')),
                ('credencial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Credencial')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Papel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(max_length=20, null=True, unique=True)),
                ('cpf', models.CharField(max_length=20, null=True, unique=True)),
                ('habilidade', models.ManyToManyField(to='backend.Habilidade')),
                ('organizacao', models.ManyToManyField(to='backend.Organizacao')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaPapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Papel')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.PessoaPapel')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, null=True, unique=True)),
                ('descricao', models.CharField(max_length=20, null=True, unique=True)),
                ('dataInicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracao', models.TimeField()),
                ('ferramenta', models.ManyToManyField(to='backend.Ferramenta')),
            ],
        ),
        migrations.AddField(
            model_name='pessoaprojeto',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Projeto'),
        ),
    ]
