# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoapapel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
