# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160510_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaprojeto',
            name='papel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Papel'),
        ),
        migrations.AlterField(
            model_name='pessoapapel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pessoaprojeto',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Pessoa'),
        ),
    ]
