# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160510_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoapapel',
            name='papel',
        ),
        migrations.RemoveField(
            model_name='pessoapapel',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='PessoaPapel',
        ),
    ]
